export const CATEGORIES: string[] = [
  'İsim (Erkek)',
  'İsim (Kadın)',
  'Şehir (Türkiye)',
  'Şehir (Dünya)',
  'Ülke (Dünya)',
  'Başkent',
  'Hayvan',
  'Bitki / Çiçek',
  'Meyve / Sebze',
  'Eşya',
  'Marka',
  'Araba Markası',
  'Teknoloji Markası',
  'Ünlü (Sanatçı / Oyuncu)',
  'Şarkıcı / Müzik Grubu',
  'Film',
  'Dizi',
  'Çizgi Film / Animasyon Karakteri',
  'Kitap',
  'Yazar',
  'Meslek',
  'Spor Dalı',
  'Futbol Takımı',
  'Futbolcu',
  'Yemek / Tatlı',
  'İçecek',
  'Renk',
  'Giysi / Aksesuar',
  'Müzik Aleti',
  'Bilim İnsanı / Mucit',
  'Dağ / Nehir / Göl',
  'Mitolojik Karakter',
  'Peri Bacaları / Turistik Yer',
]
